### PR TITLE
Fix random seed

### LINKED ISSUE #100: Same cipher every day
**Describe the bug**
Every day uses the same cipher.

**To Reproduce**

1. Solve today's cryptogram
2. Open a new window and click on the calendar and select yesterday's cryptogram.
3.Solve yesterday's cryptogram
4. Compare the alphabets of both cryptograms.  They will be the same.

**Expected behavior**
Each day should have a distinct random key.

**Screenshots**
Screen Shot 2024-03-08 at 11 07 33 AM
1167732/57f67ada-338e-4085-a4e2-c3eec605efd9)

Screen Shot 2024-03-08 at 11 20 25 AM

Note that in two different cryptograms "ZOO" = "ALL"

### PR DESCRIPTION
**Pull request by cesine**
fixes #100

### CODE REVIEW

File: src/App.tsx [hunk 1]
```diff
@@ -151,18 +152,20 @@ function App() {
...
-          if (input === cipher[key].decrypted) {
-            onChar(cipher[key].decrypted, key)
-          } else {
-            debug(
-              'this was an incorrect guess, we arent sure where to put it ',
-              input
-            )
-          }
+      guesses
+        .filter(({ status }) => status === 'correct')
```
Comment (cesine) [inline src/App.tsx:156]: This was a bug fix where if you guessed an incorrect letter, it was re-populating on page reload as a correct guess because we werent checking the status

File: src/lib/cipher.ts [hunk 2]
```diff
@@ -54,7 +54,7 @@ function isOriginalPosition(shuffled: string[], original: string[]) {
 }
 
 function seededRandom(seed: number) {
-  const x = Math.sin(seed++) * 10000
```
Comment (cesine) [inline src/lib/cipher.ts:57]: This was mutating the argument which is not permitted in modern javascript, the augmendted seed wasnt actually changing and the number was the same for each letter of the alphabet so the cipher was just sorted backwards.
